// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtgapupburfphqrcftxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Z2FwdXBidXJmcGhxcmNmdHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzUyMzAsImV4cCI6MjA3MjgxMTIzMH0.qo731FZg3fsyNrJnj4semTIx4qH0aOm7ALr90GH8_nU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});